#!/bin/bash
#
#  Get timngs for the push/pull communications pattern.

nummsgs=100000    # Seems good.
echo =============== Timing push/pull communications > pushtimings.txt # makes new file.

for endpoint in tcp://127.0.0.1:3000 ipc:///tmp/pair inproc:///pair
do 
    echo Timings for $endpoint >> pushtimings.txt
    for  size in 1024 2048 4096 8192 16384 32768 65536 131072 262144 524288 1048576
    do
        for pullers in 1 2 3 4 5
        do
            echo ---- pullers: $pullers size: $size >>  pushtimings.txt
            ./push $endpoint $nummsgs $pullers $size >> pushtimings.txt
        done
    done
done